version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: sergepogorelov/foodgram:v1
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
      
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - web
    ports: 
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
